### ISSUE TITLE
Compilers not available

### ISSUE THREAD

**Issue by xansec** [GH0st3rs/cross-toolchains#5]
It appears to be using distcc but is not available when run:

```
$ docker run -td -p 3623:3623 powerpc-linux-gnu
7bd4dbc610388d8cb7af23373008e5b6e0e8d3cc211a4eaec68e3b0a2e152ab2

$ docker container inspect -f '{{ .NetworkSettings.IPAddress }}' youthful_cori 
172.17.0.3

$ export DISTCC_HOSTS=172.17.0.3

$ distcc powerpc-linux-gnu-gcc hey.c 
distcc[1117400] (dcc_execvp) ERROR: failed to exec powerpc-linux-gnu-gcc: No such file or directory
distcc[1117399] ERROR: compile hey.c on localhost failed with exit code 110
```

**Comment by GH0st3rs** [comment]
Hello, I suppose you don't have `powerpc-linux-gnu-gcc` on your localhost.

**Comment by xansec** [comment]
Do I have to have it on my localhost? Maybe I misunderstood, I thought the whole point of this repo was to make cross-compilers available in docker containers via distcc. You're correct, btw:

Localhost:
```
$ powerpc-linux-gnu-gcc
bash: powerpc-linux-gnu-gcc: command not found
```
PPC Docker container:
```
$ docker exec -it youthful_cori /bin/bash
root@7bd4dbc61038:/tmp# powerpc-linux-gnu-gcc
powerpc-linux-gnu-gcc: fatal error: no input files
compilation terminated.
```

If I'm misunderstanding something, how do I get `powerpc-linux-gnu-gcc` available on my host? Do I simply copy it from inside the container?

**Comment by GH0st3rs** [comment]
Yes, if you want to use `distcc` you must have the same compilers on your client (localhost) and server (docker).
If you really want learn how distcc works, I recommend you read about it on the Gentoo or Archlinux Wiki.

Of course you can use the cross-compilers in docker without distcc.

> If I'm misunderstanding something, how do I get powerpc-linux-gnu-gcc available on my host? Do I simply copy it from inside the container?

One case for instance: you have a low-cpu PowerPC device with `powerpc-linux-gnu-gcc`, which means you can use distcc on that device + the docker container on your localhost to speed up the compilation process

**Comment by xansec** [comment]
Ok, so it seems to me the intended use case if you do not have the cross-compiler is to copy the files into the docker container, compile them, and them copy them out. If you don't mind, a one or two line explanation in the readme would be helpful so that others don't go trying the distcc route if it isn't the intended use case. Thanks

**Comment by GH0st3rs** [comment]
You not have to move your files into the docker.
1) you can use mounted directory in docker
2) you can execute: `docker run -it powerpc-linux-gnu powerpc-linux-gnu-gcc file.c`

There are many way to use it

**Comment by xansec** [comment]
Ok. It wasn't clear based on the readme how I was supposed to use the containers. I think I get it now. We can close this.
